### ISSUE TITLE
pilot status raises TypeError: task_list() got an unexpected keyword argument 'num_results' 

### ISSUE THREAD

**Issue by byee4** [globus/globus-pilot#148]
Hello! 

I've been following the "Django portal framework" which has so far proven to be very useful! However, upon setting up the recommended search workflow with pilot, it appears that I've hit an error:

```
(jupyter) [bay001@tscc-1-0 ~]$ pilot upload my_data.tsv test_dir --verbose -j my_metadata.json
Uploading my_data.tsv using globus... 
A transfer has been queued, see `pilot status` for an update of the transfer.
(jupyter) [bay001@tscc-1-0 ~]$ pilot status
Updating tasks...
Traceback (most recent call last):
  File "/home/bay001/anaconda2/envs/jupyter/bin/pilot", line 8, in <module>
    sys.exit(cli())
  File "/home/bay001/anaconda2/envs/jupyter/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/bay001/anaconda2/envs/jupyter/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/bay001/anaconda2/envs/jupyter/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bay001/anaconda2/envs/jupyter/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bay001/anaconda2/envs/jupyter/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/bay001/anaconda2/envs/jupyter/lib/python3.7/site-packages/pilot/commands/transfer/status_commands.py", line 47, in status_command
    update_tasks(pending_tasks)
  File "/home/bay001/anaconda2/envs/jupyter/lib/python3.7/site-packages/pilot/commands/transfer/status_commands.py", line 21, in update_tasks
    tc.task_list(num_results=100).data}
TypeError: task_list() got an unexpected keyword argument 'num_results'
```

**Comment by NickolausDS** [comment]
Hello and thanks for submitting this bug!

Pilot started as our initial approach for associating records in Globus Search to data on a Globus Collection, but due to its focus on individual records we've started to move towards other approaches for ingest into portals. Django Globus Portal Framework has recently [changed its documentation](https://django-globus-portal-framework.readthedocs.io/en/latest/tutorial/search/index-creation.html#creating-the-index) to recommend these approaches instead:
1. Individual ingest using the Globus CLI
1. Scripts to ingest large batches of records into Globus Search at once
3. Running Globus Flows to ingest records as a final action in a data processing pipeline


The first and third steps are documented above, and we plan to add documentation for the second use-case to DGPF in the future. Let us know if you would like more info on any approach, and I'm happy to list a preliminary example for 2. above if you need it.

**Comment by byee4** [comment]
Gotcha, thanks! Exploring option 1 now!
